parameters:
#    cms_core.example.class: CMS\CoreBundle\Example

services:
#    cms_core.example:
#        class: %cms_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
