parameters:
#    cms_backend.example.class: CMS\BackendBundle\Example

services:
#    cms_backend.example:
#        class: %cms_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
