security:
    encoders:
        CMS\BackendBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: CMSBackendBundle:User, property: username }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /profile
            logout: true
            security: true
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 120
                path:     /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
